### PR TITLE
Fix Zeitwerk reload issue

### LINKED ISSUE #67: "find_or_default" error when reloading with some plugins which use "deface" gem in Redmine 5.1 environment
I encountered the following error when reloading with some plugins which use `deface` gem in Redmine `5.1-stable` branch environment.
```
RuntimeError (There's no setting named plugin_redmine_message_customize):
  
app/models/setting.rb:361:in `find_or_default'
plugins/redmine_message_customize/app/models/custom_message_setting.rb:6:in `find_or_default'
plugins/redmine_message_customize/config/locales/custom_messages/ar.rb:1:in `load_rb'
plugins/redmine_custom_fields_groups/app/overrides/issues.rb:2:in `new'
plugins/redmine_custom_fields_groups/app/overrides/issues.rb:2:in `<module:Issues>'
plugins/redmine_custom_fields_groups/app/overrides/issues.rb:1:in `<top (required)>'
plugins/redmine_custom_fields_groups/init.rb:29:in `require_relative'
plugins/redmine_custom_fields_groups/init.rb:29:in `<top (required)>'
lib/redmine/plugin_loader.rb:31:in `load'
lib/redmine/plugin_loader.rb:31:in `run_initializer'
lib/redmine/plugin_loader.rb:108:in `each'
lib/redmine/plugin_loader.rb:108:in `block in load'
```

But, I couldn't find which plugin side causes the error, because `deface` side seems to require some hacks.
(But, sorry. I haven't checked the details about `deface` side yet... 🙇💦)
https://github.com/jbbarth/redmine_base_deface/blob/master/init.rb#L13-L39

If someone know what could be the cause, telling us is really helpful... 🙏 🙇‍♂️

Here is my minimum reproducible steps in one of our plugins which use `deface` gem.
1. Setup env
   ```sh
   git clone git@github.com:redmine/redmine.git -b 5.1-stable redmine-message-customize
   cd redmine-message-customize
   # Create and adjust config/database.yml (We are using "postgresql" adapter)
   cd plugins
   git clone git@github.com:farend/redmine_message_customize.git
   git clone git@github.com:gtt-project/redmine_custom_fields_groups.git
   cd ../
   bundle install
   bundle exec rake db:create
   bundle exec rake db:migrate
   bundle exec rake db:fixtures:load
   bundle exec rake redmine:plugins:migrate
   ```
2. Launch rails server
   ```sh
   bundle exec rails s -b 0
   ```
3. Open http://localhost:3000 with a browser, then login and move to `/projects` path.
4. Modify message customize plugin's `ja` locale file.
   ```diff
   --- a/config/locales/ja.yml
   +++ b/config/locales/ja.yml
   :
   -  label_default_messages: デフォルトのメッセージを確認する
   +  label_default_messages: デフォルトのメッセージを確認する123
   ```
5. Reload the browser, then you will see the description top error message.

### PR DESCRIPTION
**Pull request by sanak**
Fix https://github.com/farend/redmine_message_customize/issues/67

Changes proposed in this pull request:
- Better deface override definition (override each method level) from referring the following file.
  * https://github.com/nanego/redmine_customize_core_fields/blob/master/app/overrides/issues/new.rb
  * https://github.com/jbbarth/redmine_base_deface/blob/master/init.rb#L13-L39

@gtt-project/maintainer

### CODE REVIEW

**Comment by sanak** [comment]
Hmm...
Now Redmine 4.2 and master (6.0) seem to work fine, but `bundle exec rake zeitwerk:check` reports error in Redmine 5.0 and 5.1...
https://github.com/gtt-project/redmine_custom_fields_groups/actions/runs/10301118962/job/28511968966
```
NameError: uninitialized constant Issues::New
Did you mean?  News
               Net
```
I will try to solve the issue (or just skip `zeitwerk:check`) in Redmine 5.0 and 5.1 case, tomorrow.

**Comment by sanak** [comment]
@mopinfish (CC: @dkastl @smellman)
This is fix for the following message customize plugin's combination error in Redmine 5.1 environment.
https://github.com/farend/redmine_message_customize/issues/67

I am thinking to create similar PR to redmine_gtt plugin side soon, so checking this is helpful.

**Comment by sanak** [comment]
@mopinfish @dkastl @smellman 
Sorry, the last commit seems to reproduce the original issue again instead of passing `zeitwerk:check` test...
I will set draft mode for all related PRs. 🙇‍♂️

**Comment by sanak** [comment]
@mopinfish @dkastl @smellman
Well, I fixed previous commit issue with the following additional commit, so now this PR is ready for review.
commit diff: https://github.com/gtt-project/redmine_custom_fields_groups/pull/38/commits/fb3872341e443424540759fc3ff467e1f1b70851

I will set ready for other PRs as well.

**Review by mopinfish — APPROVED** [review]
LGTM

**Comment by sanak** [comment]
Thanks!
I will merge this.

**Pull request merged**
